[theme]

primaryColor="#d33682"
backgroundColor="#002b36"
secondaryBackgroundColor="#586e75"
textColor="#fafafa"
font="sans serif"

#primaryColor = "#E694FF"
#backgroundColor = "#00172B"
#secondaryBackgroundColor = "#0083B8"
#textColor = "#DCDCDC"
#font = "sans-serif" 